Feature/union source data
fivetran/dbt_xero_source pull request #11
Opened 2021-10-27 22:11 UTC by fivetran-reneeli

**Are you a current Fivetran customer?** 

Nope
**What change(s) does this PR introduce?** 

Add ability to union from multiple data sources
**Does this PR introduce a breaking change?**

- [] Yes (please provide breaking change details below.) 
- [x] No  (please provide explanation how the change is non breaking below.)
Backwards compatible

**Is this PR in response to a previously created Issue**

- [x] Yes, Issue [fivetran/dbt_xero#15]
- [] No 

**How did you test the PR changes?** 

 
- [x] CircleCi  
- [ ] Other (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2021-10-28 21:16 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli great job adding this union feature to the xero_source package! I have a few comments and requests I would like you to apply before we merge to `main`. See a checklist of the items I called out inline within the review below:
- [x] It seems the README was not updated to reflect the major version upgrade and how to use the new `union_schema` and `union_databases` variables. Can you update the README.
- [x] You made a great call out during standup to still include the `not_null` tests within the schema.yml. Can you add the relevant `not_null` tests back.
- [x] The enabled config block within the `stg_xero__credit_note_tmp` model was removed. Can you add this back in as well as take a look at my inline comment around why this is needed. This enabled config block + variable reference is heavily used throughout our packages to allow the widest range of users to leverage our packages. Let me know if you have any questions on this.
- [x] The dbt_fivetran_utils package just had the branch you are referencing be released in the latest `v0.2.8` release so you should be able to switch back to the package dependency and remove the git reference.

2021-10-28 21:16 UTC, fivetran-joemarkiewicz commented on models/stg_xero.yml
> -          - not_null
I think you brought up in standup that the `not_null` tests should still be included? Would you be able to add the `not_null` test back since we will still want to apply this test, but the unique combination of columns test not handles the uniqueness.

2021-10-28 21:16 UTC, fivetran-joemarkiewicz commented on models/stg_xero.yml
> -          - not_null
It actually looks like all the `not_null` tests were removed. Would you be able to add them back.

2021-10-28 21:16 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_xero__credit_note_tmp.sql
> +{{
It looks like you removed the enable config block. This is still needed so customers may be able to disable the model if they do not have the base `credit_note` model in their warehouse. These config blocks are always necessary in order for the package to run properly if they do not have the specific table being synced into their warehouse by Fivetran.

For example, if a customer does not have the `credit_note` source table and attempts to run this dbt package then it will fail on this model. However, if we include the below config block
```sql
{{ config(enabled=var('xero__using_credit_note', True)) }}
```
and set the `xero__using_credit_note` variable to `false` then this model will not run, and they will be able to successfully run the rest of the models in this package. Let me know if you have any questions on this 😄

2021-10-28 21:16 UTC, fivetran-joemarkiewicz commented on packages.yml
> +    warn-unpinned: false
You can switch this back to the package version since @fivetran-jamie released `v0.2.8` with those updates yesterday. 🎉

2021-10-29 17:46 UTC, fivetran-reneeli commented on models/tmp/stg_xero__credit_note_tmp.sql
> +{{
That's my bad, totally missed that. Thanks for noticing!

2021-11-01 14:29 UTC, fivetran-joemarkiewicz commented
@fivetran-reneeli feel free to re-request my review once you are ready for me to take another pass at this PR. I just reviewed and it looks like you checked the action items in my last review comment and most look good. However, I don't seem to see the README updates applied?

2021-11-01 14:53 UTC, fivetran-reneeli commented
> @fivetran-reneeli feel free to re-request my review once you are ready for me to take another pass at this PR. I just reviewed and it looks like you checked the action items in my last review comment and most look good. However, I don't seem to see the README updates applied?

@fivetran-joemarkiewicz  Thanks for calling that out, looks like I only updated the transforms readme. I've made the changes and checks have passed-- here's a sample queries to check the source relation's been added!

`SELECT * FROM `dbt-package-testing.dbt_renee_stg_xero.stg_xero__credit_note` LIMIT 1000`
`SELECT * FROM `dbt-package-testing.dbt_renee_xero.xero__profit_and_loss_report` LIMIT 1000`

2021-11-01 15:04 UTC, fivetran-joemarkiewicz commented
Thanks @fivetran-reneeli! One last thing that should be added to the README updating the package version range to fit what will be the latest version.
![image](https://user-images.githubusercontent.com/74217849/139693171-841728fe-64bd-4542-9940-77ff63fe6538.png)
Additionally, can you add a CHANGELOG with the changes included for this next release.

Then feel free to re-request my review (there should be a button near my name in GitHub that will allow you to re-request my review. I think it is the two arrows?).
![image](https://user-images.githubusercontent.com/74217849/139693427-6dd2ef4a-71d9-46be-bba4-33636bfb65ef.png)

2021-11-01 21:54 UTC, fivetran-joemarkiewicz approved these changes
Looks good!! Can you just make the super minor changes I called out in the CHANGELOG before merging. Thanks 😄

2021-11-01 21:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +- Because columns that were previously used for unique tests may now have duplicate fields across multiple sources, these columns are combined with the new `source_relation` column for unique tests a
This is a great under the hood update to include in the CHANGELOG. Great call out! 🙌

2021-11-01 21:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +  - Refer to the README for more details. (See ### Unioning Multiple Xero Connectors).
Can you instead link to that section instead? 
```suggestion
  - Refer to the [README](https://github.com/fivetran/dbt_xero_source#unioning-multiple-xero-connectors) for more details.
```
FYI the link won't work until the PR is merged.

2021-11-01 21:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +## Features
For each of the main bullets in the CHANGELOG can you include a link to the PR where the change was made. See the recent [dbt_netsuite_source CHANGELOG](https://github.com/fivetran/dbt_netsuite_source/blob/main/CHANGELOG.md) for example. 
![image](https://user-images.githubusercontent.com/74217849/139746989-af9c0dd3-29fc-4aab-a05d-28659120a87a.png)

2021-11-01 21:54 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +## Features
Additionally to the above, can you please add the section at the bottom that just points users to refer to the Github repository release notes for details on the previous releases.

2021-11-01 23:17 UTC, merged